:ruby: ree
:application: mano_browsercms
:user: rails
:group: rails
:ssl:
:self_signed: true
:deploy_to: /srv/mano_browsercms
:domain: codegreenlabs.com
:domain_aliases
  - bcms.codegreenlabs.com
:repository: git@github.com:agiletoolkit/mano_browercms.git
:local_config:
- config/database.yml
:shared_children:
- system
- log
- pids
- config
:apt_gems:
  :paperclip:
  - imagemagick
:passenger:
  :max_pool_size: 3
  :use_global_queue: true
:mysql:
  :innodb_buffer_pool_size: 128M

